

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    container_name: dev
    network_mode: "host"
    volumes:
      - ./workspace:/home/dev/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.m2:/home/dev/.m2
      - $HOME/.ssh:/home/dev/.ssh
    working_dir: /home/dev
    stdin_open: true
    tty: true
    user: "${HOST_UID}:${HOST_GID}"
    command: [ "zsh", "-l" ]
